SRC_DIR=../rop_compiler/

test:
	env PYTHONPATH=$(SRC_DIR) python classifier_tests.py
	env PYTHONPATH=$(SRC_DIR) python validator_tests.py
	env PYTHONPATH=$(SRC_DIR) python gadget_tests.py
	env PYTHONPATH=$(SRC_DIR) python bof_tests.py
